services:
  opensigl:
    image: ghcr.io/eyanoapp/opensigl:latest
    restart: unless-stopped
    ports:
      - "8080:${PORT:-8080}"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_USER=${DB_USER:-opensigl}
      - DB_NAME=${DB_NAME:-opensigl}
      - DB_PASS=${DB_PASS:-cbeec29bac2f7726e1355c5a5bf10f35963cac8e77ed763bf2}
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  mysql:
    image: mysql:9.2
    restart: unless-stopped
    command:
      - --sql-mode=STRICT_ALL_TABLES,NO_UNSIGNED_SUBTRACTION
    volumes:
      - mysqldata:/var/lib/mysql/
      - ./server/models:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USER:-opensigl}
      - MYSQL_DATABASE=${DB_NAME:-opensigl}
      - MYSQL_PASSWORD=${DB_PASS:-cbeec29bac2f7726e1355c5a5bf10f35963cac8e77ed763bf2}
    networks:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:

volumes:
  mysqldata:
